### ISSUE TITLE
React as a peerDependency really needed?

### ISSUE THREAD

**Issue by donaldpipowitch** [danmartinez101/babel-preset-react-hmre#19]
Hi, is it really needed to declare React as a dependency here? It is not used directly and it should be possible to use babel-preset-react-hmre, if it is nested inside some other node_modules.
https://github.com/danmartinez101/babel-preset-react-hmre/blob/master/package.json#L16

E.g. this should be possible:

```
my-app/
 - src/
 - node_modules/
    - react/
    - some-build-tool/
       - node_modules/
          - babel-preset-react-hmre/ // not at the same level as react, but should work anyway, if configured correctly
```

**Comment by gaearon** [comment]
Fair enough; just killed it in 73924d08da9d553b03505867357ac0d868563936.

**Comment by donaldpipowitch** [comment]
Nice. Thank you.
