### ISSUE TITLE
Update readme with usage instructions when HMR supports babel 6

### ISSUE THREAD

**Issue by danmartinez101** [danmartinez101/babel-preset-react-hmre#2]
Tracking https://github.com/gaearon/babel-plugin-react-transform/pull/50

**Comment by jedmao** [comment]
Why was this closed? Is there a working example with Babel 6 yet?

**Comment by danmartinez101** [comment]
Sorry, I probably should have commented when closing this to say: 

Support for Babel 6 has been added to the underlying dependencies so I'm going to close this issue now.
