### ISSUE TITLE
npm warning with React 15-rc1

### ISSUE THREAD

**Issue by ghost** [danmartinez101/babel-preset-react-hmre#23]
I am using React 15-rc.1 and have the following warning originating from `babel-preset-react-hmre`:
```
npm WARN redbox-react@1.2.2 requires a peer of react@>=0.13.2 || ^0.14.0-rc1 but none was installed.
```

**Comment by danmartinez101** [comment]
Thanks for the heads up!

There is a [pull request](https://github.com/KeywordBrain/redbox-react/pull/48) to resolve this issue which originates in https://github.com/KeywordBrain/redbox-react.

I'm going to close this as greenkeeper will send a PR to update here when the new version is available there.

**Comment by danmartinez101** [comment]
Actually, let's keep this open until the fix is merged.

**Comment by geekyme** [comment]
Waiting on this too :)

**Comment by danmartinez101** [comment]
https://circleci.com/gh/danmartinez101/babel-preset-react-hmre/37 is pulling in redbox-react@1.2.3 so this should be good to go.
