### ISSUE TITLE
Add `createClass` inside `factoryMethods` options

### ISSUE THREAD

**Issue by wmonk** [danmartinez101/babel-preset-react-hmre#24]
Hi,

At the moment [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform/) does not support `createClass` by default, only `React.createClass`.

It would be nice to move to use this plugin, to keep up to date with transforms, but without support for `createClass` on it's own I can't. 

Not sure if this should be solved in [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform/) by adding `createClass` to the defaults for `factoryMethods`. I started drafting a pull request and issue, but thought I'd go to the immediate source.

I can add a pull request if you would like - or alternatively @gaearon I can add it to babel-plugin-react-transform.

Incase this doesn't make sense here is a quick bit of code to illustrate:

```
import React, { createClass } from 'react';
export default createClass({ 
    render() { 
        return (<div>Hi!</div>) 
    } 
});
```

Thanks! :)

**Comment by danmartinez101** [comment]
I think that I'd like to keep this preset as just the minimal default config for the two contained babel plugins. In that spirit, I'd say that if this was going to be added to the defaults, I'd prefer it be downstream of this preset. 

Those are my two cents but if @gaearon has a different opinion, I'd be open to that as well.

**Comment by wmonk** [comment]
I think I would agree with this - I will open an issue/pull req there. Thanks.

**Comment by danmartinez101** [comment]
Closing this as it looks like things are rolling in react-transform
