### ISSUE TITLE
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled.

### ISSUE THREAD

**Issue by ahmed1490** [danmartinez101/babel-preset-react-hmre#25]
Setup done with `react-hmre` preset with hapi js.

Example config setup: http://www.webpackbin.com/Ey_d9Jong (its not intended to run there)

Screenshot of the error:
<img width="1265" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/13687482/d90c91b2-e71b-11e5-83b7-fbba0db045d9.png">

I did add HotModuleReplacement as mentioned here: https://github.com/danmartinez101/babel-preset-react-hmre/issues/16#issuecomment-185885789

Am I missing something?

**Comment by ahmed1490** [comment]
Not sure if this issue belongs to the react-transform-hmr. I will create an issue there as well.

**Comment by wmonk** [comment]
This should not be used when running on the server. I've had this issue when compiling server code and using react-transform-hmr.

**Comment by gaearon** [comment]
Please see:
https://github.com/gaearon/react-transform-boilerplate#should-i-run-this-on-the-server--in-tests--in-production
