### ISSUE TITLE
cannot refresh page or browse to another endpoint after rebuild

### ISSUE THREAD

**Issue by zdelagrange** [danmartinez101/babel-preset-react-hmre#29]
the react-hmre preset works pretty well if you developing on one page and do not need to browse to other endpoints in the app or refresh the page. When this happens, the console log outputs this error:

Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by danmartinez101** [comment]
Can you please create a small sample application the demonstrates this error? I'm happy to try to track down the problem, but I don't currently have any projects using react so I'm unlikely to run across this on my own. Thanks!

**Comment by danmartinez101** [comment]
@zdelagrange I'm going to have some time this coming week to work on this project. Is this still an issue for you, or do you figure out what was going wrong?

**Comment by danmartinez101** [comment]
Please see https://github.com/danmartinez101/babel-preset-react-hmre/issues/46#issuecomment-250945091

Basically, happy for a PR and to help you get your fixes published.
