### ISSUE TITLE
when I update my code ,  the component duplicate.

### ISSUE THREAD

**Issue by tyzero** [danmartinez101/babel-preset-react-hmre#34]
if I update the  component twice, I the browser, that component will duplicate twice.
just like:

# Search Github User 2
# Search Github User 2

**Comment by danmartinez101** [comment]
Please see https://github.com/danmartinez101/babel-preset-react-hmre/issues/46#issuecomment-250945091

Basically, happy for a PR and to help you get your fixes published.
