### ISSUE TITLE
Breaks transform-decorators-legacy plugin

### ISSUE THREAD

**Issue by corbanbrook** [danmartinez101/babel-preset-react-hmre#38]
```Decorators are not supported yet in 6.x pending proposal update.```

This preset and babel 6.5.* work fine with babel-plugin-transform-decorators-legacy but does not work with latest babel 6.9.*

**Comment by danmartinez101** [comment]
Please see https://github.com/danmartinez101/babel-preset-react-hmre/issues/46#issuecomment-250945091

Basically, happy for a PR and to help you get your fixes published.
