### ISSUE TITLE
React-transform-hmr is deprecated.

### ISSUE THREAD

**Issue by ZhuGongpu** [danmartinez101/babel-preset-react-hmre#40]
React-transform-hmr is deprecated now.
So, what`s next?

And it seems actions can not be hot reloaded as components and reducers do. Is React Hot Loader 3 required for this issue?

**Comment by danmartinez101** [comment]
Yes, that is an option. Please see https://github.com/gaearon/react-hot-boilerplate/issues/97#issuecomment-249862775
