### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by danmartinez101** [danmartinez101/babel-preset-react-hmre#46]
## The Situation

Dan explained it well for RHL : https://github.com/gaearon/react-hot-boilerplate/issues/97#issuecomment-249862775 
React Amazed; Hot Reloading got Hot;  Boilerplate went Viral; [CRA](https://github.com/facebookincubator/create-react-app) ~ Anti-viral 

This repo was created to reduce boilerplate config in RHL: 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Anytime the objection is &quot;too much boilerplate,&quot; the typical solution will make you smile today and tear your hair out 6 months from now.</p>&mdash; Richard Feldman (@rtfeldman) <a href="https://twitter.com/rtfeldman/status/781973210434707456">September 30, 2016</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

## The Ask
I'm reaching out to @reactjs based on the principles to see if this fits into that organization or elsewhere. I'm working in a different focus-area and I'm not engaged here; However, there are about 4k repos installing it and I'd like help to ensure things go down smoothly.

@reactjs 
  @chefsplate chefsplate / babel-preset-react-hmre
  @dagostinelli dagostinelli / babel-preset-react-hmre
  @geekyme geekyme / babel-preset-react-hmre
  @joshuahhh joshuahhh / babel-preset-react-hmre
  @macklinu macklinu / babel-preset-react-hmre
  @Massdrop Massdrop / babel-preset-react-hmre
  @pebblecode pebblecode / babel-preset-react-hmre

## Quick Links & Stats
[![NPM](https://nodei.co/npm-dl/babel-preset-react-hmre.png?height=3)](https://nodei.co/npm/babel-preset-react-hmre/)

https://libraries.io/npm/babel-preset-react-hmre
<img width="383" alt="screen shot 2016-10-01 at 7 31 31 am" src="https://cloud.githubusercontent.com/assets/2669819/19013787/27f98018-87a9-11e6-929d-e70681ef39bc.png">

**Comment by dagostinelli** [comment]
IMO: Yes, this project belongs part of some larger thing.

Like this one: https://github.com/babel/babel/tree/master/packages

**Comment by danmartinez101** [comment]
I was so far removed that I mistook this as being related to the version that was *not* deprecated. 
This was thankfully cleared up in https://github.com/gaearon/react-hot-loader/issues/385#issuecomment-250941283 

My apologies to those of you who's time I wasted with this folly.

The only project the supports being deprecated, I'm going  to do nothing with it. My concern of this need a maintainer seems to be solved by the upgrade paths of the main projects.

If any current users would like to take ownership, that is up for grabs. I certainly do not thinks this belongs in the reactjs org.
