### ISSUE TITLE
Use alternative to redbox?

### ISSUE THREAD

**Issue by gaearon** [danmartinez101/babel-preset-react-hmre#8]
There are some problems with redbox-react: it's not currently actively maintained and it doesn't work in Safari. We should either fix redbox-react, or look into an alternative solution as the default.

**Comment by danmartinez101** [comment]
The options look to be:
1. https://github.com/KeywordBrain/redbox-react/pull/40 gets merged
2. https://github.com/danmartinez101/babel-preset-react-hmre/pull/9

@gaearon How long do you think it is worth waiting to see if option 1 gets merged before swapping it out for option 2?

**Comment by gaearon** [comment]
David graciously provided me access to the repo so I'll merge Safari support soon.

**Comment by danmartinez101** [comment]
Excellent :D

**Comment by danmartinez101** [comment]
Closing this issue since the PR was merged. I'll have a release out within 24 hours.
